name: Local Config
version: 1.0.0
models:
  - name: 🤖 LM Studio - Nemotron Nano
    provider: lmstudio
    model: nvidia/nemotron-3-nano-4b
    apiBase: http://localhost:1234/v1
    roles:
      - chat
      - edit
  - name: 🤖 LM Studio - Gemma 4 2B
    provider: lmstudio
    model: google/gemma-4-e2b
    apiBase: http://localhost:1234/v1
    roles:
      - chat
      - edit
  - name: 🤖 LM Studio - Ministral 3B
    provider: lmstudio
    model: mistralai/ministral-3-3b
    apiBase: http://localhost:1234/v1
    roles:
      - chat
      - edit
  - name: 🦙 Ollama - Qwen 3.5 2B
    provider: ollama
    model: qwen3.5:2b
    apiBase: http://localhost:11434
    roles:
      - chat
      - edit
  - name: 🦙 Ollama - Gemma4 2B
    provider: ollama
    model: gemma4:e2b-it-q4_K_M
    apiBase: http://localhost:11434
    roles:
      - chat
      - edit
  - name: 🦙 Ollama - GLM 4.7 Flash
    provider: ollama
    model: glm-4.7-flash:q4_K_M
    apiBase: http://localhost:11434
    roles:
      - chat
      - edit
  - name: Autodetect
    provider: lmstudio
    model: AUTODETECT
    apiBase: http://localhost:1234/v1/
