[windows_standard]
192.168.100.60

[windows_dev]
192.168.100.70

[windows:children]
windows_standard
windows_dev

[windows:vars]
ansible_user=Administrator
ansible_password=REDACTED_PASSWORD
ansible_connection=winrm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
